package com.dab.docscoring.hibernate.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.NamedQuery;

/**
 * Companies generated by hbm2java
 */
@Entity
@Table(name = "companies", catalog = "documentscoring", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
@NamedQuery(name="Company.findAll", query="from Company")
public class Company implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private Integer id;
	private String name;
	private boolean entitled;
	private String password;

	public Company() {
	}

	public Company(String name, boolean entitled, String password) {
		this.name = name;
		this.entitled = entitled;
		this.password = password;
	}

	public Company(String name, boolean entitled, String password, User users) {
		this.name = name;
		this.entitled = entitled;
		this.password = password;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", unique = true, nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "ENTITLED", nullable = false)
	public boolean isEntitled() {
		return this.entitled;
	}

	public void setEntitled(boolean entitled) {
		this.entitled = entitled;
	}

	@Column(name = "PASSWORD", nullable = false, length = 16)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
}